### ISSUE TITLE
[Feature suggestion] Markdown support

### ISSUE THREAD

**Issue by noraj** [CervantesSec/cervantes#16]
It would be nice to have Markdown support for vulnerability text fields as alternative to HTML.

Using HTML or Markdown could be set up globally in the admin area. Or using HTML or Markdown could be chose per vulnerability during the vulnerability creation.

Markdown is meant to be transpilled as HTML and markdown renderers can accept HTML tags and forwards them so storing markdown would be backward compatible with vulns storing HTML. Generating the report  would be Markdown -> HTML -> OOXML then. It's not an issue to mix the formats for differents vulnerabilities as long a the format is tagged.

For example (high level idea of the stucture):

```yaml
vulns:
  - vuln1:
    format: html
    title: xxx
    description: "<b>bold</b>"
    cvss: xxx
  - vulns2
    format: markdown
    title: xxx
    description: "**bold**"
    cvss: xxx

```

As most pentesters use markdown, that github issues/comment are using markdown, HackerOne issue are using markdown, etc. having markdown here would facilitate a lot.
